#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

require __DIR__ . '/vendor/autoload.php';
$config = \codemix\yii2confload\Config::bootstrap(__DIR__);

$exitCode = Yii::createObject(\yii\console\Application::class, [$config->console()])->run();
exit($exitCode);
